server:
    port: 8762
spring:
    application:
        name: netflix-eureka-naming-server    
eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8762/eureka

